name: publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: CommonEnv
    
    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.PAT_TOKEN}}
    - name: Setup .NET Core SDK 3.1.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.x'
    - name: Restore .Net
      run: dotnet restore
    - name: Configure version
      run: |
        git fetch --unshallow
        lastTag=$(git describe --tags --abbrev=0)
        lastTagMainVersion=$(sed -n 's/^\([0-9]*\.[0-9]*\).*/\1/p' <<<"$lastTag")
        currentVersion=$(cat VERSION)
        currentMainVersion=$(sed -n 's/^\([0-9]*\.[0-9]*\).*/\1/p' <VERSION)
        if [ "$lastTagMainVersion" = "$currentMainVersion" ]
        then
          echo "Version the same."
          lastTagBuildVersion=$(sed -n 's/^[0-9]*\.[0-9]*\.\([0-9]*\).*/\1/p' <<<"$lastTag")
          newBuildVersion=$((lastTagBuildVersion+1))
          newVersion="$lastTagMainVersion"."$newBuildVersion"
          echo "newVersion=$newVersion"
          echo "newVersion=$newVersion" >> $GITHUB_ENV
        else
          echo "New version!"
          newVersion="$currentMainVersion".1
          VersionPrefix=$newVersion
          echo "newVersion=$newVersion"
          echo "newVersion=$newVersion" >> $GITHUB_ENV
        fi
    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{env.newVersion}}
    - name: Build
      run: dotnet build UnityMVVM.sln --no-dependencies --output build
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
       name: Build
       path: build
